# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
    ]
#t = Treasure(name='Coffee can', value=20.00, location='Acme,CA', material='tin', img_url = 'static/images/coffee-can.png')
#t.save()
#t = t = Treasure(name = 'Gold Nugget', value = 500, material = 'gold', location = "Curly's Creek, NM", img_url = '/static/images/nugget.png')
#t.save()
#t = t = Treasure(name = "Fool's Gold", value = 0, material ='pyrite', location = "Fool's Falls, CA", img_url = '/static/images/fools-gold.png')
#t.save()